### ISSUE TITLE
4. Änderung 

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/bau#5]
- [x] Welcome: Bitte den Text ändern von "Interessenvertreter" in "Interessenvertretung" sowie "und weiteren am Bau Beteiligten" in "sowie weiteren an der Planung und am Bau Beteiligten"
- [x] Welcome: Der Button 'mehr erfahren' ist cool.. (bei Herzlich Willkommen) Aber nochmal raus nehmen, da wir (noch) keinen Content haben dafür.
- [x] Schrift oben links bei den sechs Fotos raus
- [x] Die Reihenfolge im Header stimmt nicht mit dem OnePager überein.
- [x] Die Mitgliedslogos würde ich kleiner wählen, die sind recht groß und sperrig. Kann man da einen Spider einfügen bei den Logos? 
- [x] News: Hier dürfen die externen Beiträge nur auf die Original-Beiträge verlinken
- [x] Das Impressum fehlt
- [x]  Link zu Easyverein (bei 'Mitglied werden) einbinden -> hier am besten direkt mit Roland abstimmen

**Comment by codeispoetry** [comment]
Hallo Marco,

-  Die Reihenfolge im Header stimmt nicht mit dem OnePager überein.
**Den Punkt verstehe ich nicht. Meinst Du "WELCOME, MITGLIEDSCHAFT, VORSTAND,LEITBILD,NEWS, KONTAKT,IMPRESSUM"? Welche Reihenfolge soll das werden?**

-  Die Mitgliedslogos würde ich kleiner wählen, die sind recht groß und sperrig. Kann man da einen Spider einfügen bei den Logos?
**Einen Slider gibt es da leider nicht**

- Impressum
**Ist eingefügt, das befüllt ihr am besten selbst mit dem richtigen Inhalt**

**Comment by digitalesbauwesen** [comment]
"Die Reihenfolge stimmt nicht" soll folgendes bedeuten: Wenn man langsam die Seite von oben nach unten scrollt, dann sollten die Reiter ebenfalls von links nach rechts scrollen. Momentan springen die Navigationsreiter...

Kannst du uns bitte noch den Link schicken? Die Seite ist aktuell nicht erreichbar...

**Comment by codeispoetry** [comment]
Hallo,

was meinst Du mit Navigationsreiter? Das Menü ganz oben? Was springt denn da genau? Die bewegen sich doch gar nicht und scollen auch nicht.

Die Seite ist auf Wunsch von Marco offline. Man muss ich einloggen, um sie zu sehen

**Comment by digitalesbauwesen** [comment]
OK, es ist offenbar sehr schwer zu verstehen. Ich probiere es erneut: Scrolle bitte mal langsam die Seite runter und achte darauf, was oben in der Navigation passiert. Ja, ich meine das Menü oben. Erst ist der erste Punkt unterstrichen, dann der 2., dann der 3. und irgenwann "springt" die Unterstreichung nicht zum nächsten rechts daneben sondern zwei Felder weiter und dann plötzlich wieder ein Feld nach links. Kannst du das nachvollziehen? Weißt du, was ich meine? Ansonsten wäre es vielleicht gut, wenn wir mal kurz telefonieren...
