### ISSUE TITLE
5. Änderung

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/bau#6]
- [x] Beschreibungstexte der anderen Mitglieder auch unterbringen (so wie bei mir) 
- [x] Bevor sich das Startbild aufbaut, steht weiß auf schwarz "BDBAU" auf der Seite. Kann das in "BDBau" geändert werden?
-> **bietet das Theme nicht an**
- [x] Presse
- [x] Der Mann mit VR-Brille schaut nach oben recht, also wäre die Platzierung an der Postiion 4 besser geeignet.
- [x] Klick auf die Bilder öffnet die Großansicht. Brauchen wir das? Hat das einen Mehrwert? Hmm, weiß nicht. Kann man das an der Stelle ausblenden? Und vielleicht auf einer Unterseite, wo es um Event-Berichterstattung geht wieder freischalten? Anm.: Können wir die große Ansicht ausblenden? Also nur das lassen, wenn man mit der Maus über die Bilder geht, dass das Bild dann minimal größer wird. Aber die Großansicht bei Klick raus nehmen.
-> **Bietet das Theme nicht an. Bisher waren da erklärende Texte angedacht**
- [x] Bitte Mitgliedsantrag in neuem Fenster öffnen
-> **bietet das Theme nicht an**
- [x] Bitte alphabetisch sortieren
- [x] News: Da ist eine Zeile über der Navigation. Die bitte rausnehmen
- [x] Kann die Navigationszeile weiß hinterlegt sein? Also so, dass die Navigationselemente gut sichtbar bleiben?
-> **bietet das Theme nicht an**
- [x] Kann "index.php" aus der URL rausgenommen werden?
- [x] Autorenseite entfernen
- [x] Kategorie: Die Seite ist leider auch nicht formatiert. Die Überschrift ragt ins Bild hinein
-> **dafür braucht es ein anderes Bild ohne

**Comment by digitalesbauwesen** [comment]
- Wenn das Theme "BDBau" nicht anbietet, dann ändere das bitte in "BUNDESVERBAND DIGITALES BAUWESEN (BDBAU) E.V."
- Bilder-Ansicht. Gibt es die Möglichkeit, die Bilder anders darzustellen ohne Galeriefunktion?
- Wenn "öffnen in neuem Fenster" nicht möglich ist, besteht dann die Möglichkeit, auf diesen eh schon ziemlich eigenartigen Button zu verzichten und per HTML einen statischen Button mit "öffnen in neuem Fenster" einzufügen?
- Navigationszeile weiß hinterlegen -> fällt dir da ein kreativer Workaround ein?
